layerList = ( {"default":{"zoom" : 10}}
              #, {"amenity_points":{"zoom" : 10}}
              #, {"water_lines_low_zoom":{"zoom" : 10}}
              #, {"landcover":{"zoom" : 10}}
              #, {"roads_low_zoom":{"zoom" : 10}}
              #, {"text":{"zoom" : 10}}
              #, {"glaciers_text":{"zoom" : 10}}
              #, {"highway_junctions":{"zoom" : 10}}
              #, {"admin_other":{"zoom" : 10}}
              #, {"cliffs":{"zoom" : 10}}
              #, {"highway_area_casing":{"zoom" : 10}}
              #, {"nepopulated":{"zoom" : 10}}
              #, {"amenity_points_poly":{"zoom" : 10}}
              #, {"stations":{"zoom" : 10}}
              #, {"water_lines":{"zoom" : 10}}
              #, {"power_minorline":{"zoom" : 10}}
              #, {"admin_5678":{"zoom" : 10}}
              #, {"stations_poly":{"zoom" : 10}}
              #, {"water_lines_casing":{"zoom" : 10}}
              #, {"building_text":{"zoom" : 10}}
              #, {"placenames_small":{"zoom" : 10}}
              #, {"roads_text_name":{"zoom" : 10}}
              #, {"piers_area":{"zoom" : 10}}
              #, {"highway_area_fill":{"zoom" : 10}}
              #, {"tunnels":{"zoom" : 10}}
              #, {"admin_text":{"zoom" : 10}}
              #, {"turning_circle_fill":{"zoom" : 10}}
              #, {"placenames_large":{"zoom" : 10}}
              #, {"landuse_overlay":{"zoom" : 10}}
              #, {"amenity_symbols":{"zoom" : 10}}
              #, {"castlewalls_poly":{"zoom" : 10}}
              #, {"citywalls":{"zoom" : 10}}
              #, {"necountries":{"zoom" : 10}}
              #, {"power_poles":{"zoom" : 10}}
              #, {"coast_poly":{"zoom" : 10}}
              #, {"turning_circle_casing":{"zoom" : 10}}
              #, {"waterway_bridges":{"zoom" : 10}}
              #, {"roads_casing":{"zoom" : 10}}
              #, {"power_line":{"zoom" : 10}}
              #, {"theme_park":{"zoom" : 10}}
              #, {"roads_text_ref":{"zoom" : 10}}
              #, {"locks":{"zoom" : 10}}
              #, {"piers":{"zoom" : 10}}
              #, {"area_barriers":{"zoom" : 10}}
              #, {"placenames_medium":{"zoom" : 10}}
              #, {"amenity_symbols_poly":{"zoom" : 10}}
              #, {"admin_01234":{"zoom" : 10}}
              #, {"trams":{"zoom" : 10}}
              #, {"placenames_capital":{"zoom" : 10}}
              #, {"water_lines_text":{"zoom" : 10}}
              #, {"water_areas":{"zoom" : 10}}
              , {"roads_fill":{"zoom" : 10}}
              #, {"housenames":{"zoom" : 10}}
              #, {"roads_area_text_name":{"zoom" : 10}}
              #, {"interpolation":{"zoom" : 10}}
              #, {"builtup":{"zoom" : 10}}
              #, {"dam":{"zoom" : 10}}
              #, {"landcover_line":{"zoom" : 10}}
              #, {"nature_reserve_boundaries":{"zoom" : 10}}
              #, {"buildings_lz":{"zoom" : 10}}
              #, {"line_barriers":{"zoom" : 10}}
              #, {"castlewalls":{"zoom" : 10}}
              #, {"buildings":{"zoom" : 10}}
              #, {"world":{"zoom" : 10}}
              , {"ferry_routes":{"zoom" : 10}}
              , {"bridges":{"zoom" : 10}}
              #, {"sports_grounds":{"zoom" : 10}}
              #, {"marinas_area":{"zoom" : 10}}
              #, {"paths_text_name":{"zoom" : 10}}
              #, {"aerialways":{"zoom" : 10}}
              #, {"power_towers":{"zoom" : 10}}
              #, {"roads_text_ref_low_zoom":{"zoom" : 10}}
              #, {"housenumbers":{"zoom" : 10}}
              #, {"text_poly":{"zoom" : 10}}
              #, {"guideways":{"zoom" : 10}}
              #, {"water_areas_overlay":{"zoom" : 10}}
)